name: Runs tests, lints and builds the code
on:
  pull_request

jobs:
  build:
    name: Run tests, lint, build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Lint the code
        run: npm run lint
      - name: Build all libraries
        run: npm run build